name: gitleaks
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # run once a day at 1 AM
    
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Install talisman
        run: |
          curl -L https://github.com/thoughtworks/talisman/releases/download/v1.29.0/talisman_linux_amd64 -o /usr/local/bin/talisman
          chmod +x /usr/local/bin/talisman
          
      - name: Run talisman
        run: talisman --scanWithHtml