name: react JS Workflow
on: [push, workflow_dispatch]
jobs:
  Run-npm-on-Ubuntu:
    name: Run npm on Ubuntu
    run-on: Run-npm-on-Ubuntu
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Installing Node 
        uses: actions/setup-node@v4
          node-version: '18'
      - name: Installing dependencies
        run: nmp ci
      