name: React JS Workflow
on: [push, workflow_dispatch]
jobs:
  Run-Test-on-APP:
    name: Run Test on APP
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Installing Node 
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Installing dependencies
        run: npm ci
      - name: Test Script
        run: npm run test
      - name: Test Lint
        run: npm run lint

  Building-APP:
    name: Building the Code
    needs: Run-Test-on-APP
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Installing Node 
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Installing dependencies
        run: npm ci
      - name: Building Code
        run: npm run build
  Deploy-APP:
    name: Deploy the Code
    needs: Building-APP
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Installing Node 
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Installing dependencies
        run: npm ci
      - name: Deploying Code...
        run: echo "Deploying Code"